---
# tasks/shared/40_config_chrony.yml
- name: config_chrony | Configuring Chrony
  template:
    src: chrony.conf.j2
    dest: "{{ chrony_config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart {{ chrony_service }}
